#   UnlockableDimensions
#   by maurxce

# DATABASE
# types: mysql, mongodb, sqlite, nitrite, yaml
# default ports: 3306 (mysql), 27017 (mongodb)
# (none of these settings apply to yaml)
database:
  type: yaml

  host: localhost
  port: 3306

  name: unlockabledimensions
  username: ud_user
  password:

# ECONOMY POOL SETTINGS
# unlock-amount: total amount the players need to pay the pool to unlock a dimension
nether:
  enable: true
  unlock-amount: 5000

the_end:
  enable: true
  unlock-amount: 20000

# PORTAL SETTINGS
# these settings apply before the dimension goal is reached
player-portal-create: false
player-portal-enter: false

#   Support:
#   https://maurxce.dev/github
#   https://maurxce.dev/discord