#   UnlockableDimensions
#   by maurxce

# ECONOMY POOL SETTINGS
# unlock-amount: total amount the players need to pay the pool to unlock a dimension
nether:
  enable: true
  unlock-amount: 5000

the_end:
  enable: true
  unlock-amount: 20000

# PORTAL SETTINGS
# these settings apply before the dimension goal is reached
player-portal-create: false
player-portal-enter: false

#   Support:
#   https://maurxce.dev/github
#   https://maurxce.dev/discord